FROM python:3
WORKDIR /app
COPY requirements.txt ./
ENV FLASK_APP=spout.py
ENV FLASK_DEBUG=1
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "3000"]
