FROM python:3
WORKDIR /app
COPY requirements.txt ./
ENV FLASK_APP=video_processing_service.py
ENV FLASK_DEBUG=1
RUN apt-get update -y && apt-get install -y ffmpeg -y && pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
