apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ds-project
  name: video-processing-service
spec:
  selector:
      matchLabels:
          app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      containers:
      - name: video-processing-service
        image: docker-registry.default.svc:5000/ds-project/video-processing-service-prod:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: video-processing-service-env-file
        volumeMounts:
          - name: storage
            mountPath: /storage/var
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-claim


