apiVersion: v1
data:
  DATASOURCE_HOST: database
  DATASOURCE_PASSWORD: DSP2019!
  DATASOURCE_URL: jdbc:mysql://database:3306/ds_project?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  DATASOURCE_USER: springuser
  KAFKA_ADDRESS: kafkaa:9092
  KAFKA_GROUP_ID: video-management-service-group
  KAFKA_MAIN_TOPIC: videos
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DATASOURCE_HOST":"database","DATASOURCE_PASSWORD":"DSP2019!","DATASOURCE_URL":"jdbc:mysql://database:3306/ds_project?allowPublicKeyRetrieval=true\u0026useSSL=false\u0026autoReconnect=true\u0026failOverReadOnly=false\u0026maxReconnects=10","DATASOURCE_USER":"springuser","KAFKA_ADDRESS":"kafkaa:9092","KAFKA_GROUP_ID":"video-management-service-group","KAFKA_MAIN_TOPIC":"videos"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-01-13T23:39:15Z","name":"video-management-service-env-file","namespace":"ds-project","resourceVersion":"33811953","selfLink":"/api/v1/namespaces/ds-project/configmaps/video-management-service-env-file","uid":"e8e66f0c-365d-11ea-b8d0-069c1d03e046"}}
  creationTimestamp: 2020-01-14T09:25:20Z
  name: video-management-service-env-file
  namespace: ds-project
  resourceVersion: "33917386"
  selfLink: /api/v1/namespaces/ds-project/configmaps/video-management-service-env-file
  uid: c8ee1e90-36af-11ea-b8d0-069c1d03e046
